### ISSUE TITLE
在进行预测的时候报错 AttributeError: 'UIE' object has no attribute 'post_init'

### ISSUE THREAD

**Issue by Mirage7320** [taishan1994/pytorch_uie_re#4]
Traceback (most recent call last):
  File "E:\PythonProject\pytorch_uie_re\uie_test.py", line 5, in <module>
    ie = UIEPredictor('./uie_base_pytorch', schema=schema)
  File "E:\PythonProject\pytorch_uie_re\uie_predictor.py", line 135, in __init__
    self._prepare_predictor()
  File "E:\PythonProject\pytorch_uie_re\uie_predictor.py", line 143, in _prepare_predictor
    self.inference_backend = PyTorchInferBackend(
  File "E:\PythonProject\pytorch_uie_re\uie_predictor.py", line 84, in __init__
    self.model = UIE.from_pretrained(model_path_prefix)
  File "D:\Anaconda3\lib\site-packages\transformers\modeling_utils.py", line 1059, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "E:\PythonProject\pytorch_uie_re\model.py", line 88, in __init__
    self.post_init()
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UIE' object has no attribute 'post_init'

Process finished with exit code 1

**Comment by Mirage7320** [comment]
Transformer 版本问题
